#+TITLE: Regeneron STS Application Essay Questions
#+LATEX_CLASS: basic
#+LATEX_CLASS_OPTIONS: [little]
#+OPTIONS: toc:nil

* Research Project “Layperson’s Summary” (maximum 200 words)
Summarize your project in layperson’s terms, while maintaining scientific accuracy. Your explanation should be easily understandable and include background, procedures, conclusions and relevance. This summary will aid readers, including evaluators, journalists and the public.

El Niño, or ENSO, is a hugely influential climate cycle that occurs in the equatorial Pacific Ocean. It is a form of short-term climate change, so it causes certain years to be warmer or colder than others. My project shows that through greenhouse gas and aerosol emissions, human activities are causing ENSO to become stronger. I showed this by using data output by a climate model. This model uses a computer to simulate the earth's climate. By repeating this simulation with and without greenhouse gas, aerosols, and other factors, researchers have created a picture of what climate will be like over the 21^{st} century. I used this data to analyze changes to ENSO in the future by using established methods of measuring El Niño. After deducing that it was becoming stronger, I went into greater depth, analyzing what parts of ENSO are becoming stronger and why. It appears that global warming is allowing heat to spread between layers of the ocean more easily, which makes it easier for ENSO events to form. If these conclusions are correct, then we can expect more extreme weather in the future.

* Project Benefits and Impact (maximum 200 words)
What benefits do you think your research will bring to the world, and/or to your field? What additional steps, and by whom, might be needed for this benefit to be realized?

My research will improve humans' ability to prepare for ENSO in the future. My prediction that ENSO will become stronger due to greenhouse gas emissions provides additional motivation towards added protection against extreme weather. By showing that ENSO-related extreme weather will become more common in the twenty-first century, my project will encourage the construction of defenses such as flood barriers in places that are directly affected by ENSO. Additionally, my study provides an additional warning that we are only beginning to feel the negative effects of industrial emissions. Regarding the field of climatology, this study deepens our knowledge of the interaction between global warming and ENSO.

In order for the benefits of my study to be realized, my results must first be verified in other studies. Examinations with other models and with recorded data must be done to ensure that ENSO is most likely to become stronger. Additionally, examinations with higher resolution that focus on predictions for specific regions should be conducted to determine which specific cities will be most impacted and how.


* Your Potential as a Scientist, Mathematician or Engineer (maximum 250 words)
Address through specific and concrete examples what characteristics you have that best demonstrate your affinity and aptitude for being a good scientist.
- What have you done that illustrates scientific aptitude, leadership, curiosity, inventiveness and/or initiative?
- After completing your research, how has your interest in science, engineering, and/or math been clarified? What are your other STEM-related interests besides your project?
- How does your experience suggest future success as a scientist, mathematician or engineer?
- What do you plan to study in post-secondary education and what occupation do you plan to pursue?  What do you hope to be doing 10 years from now?

My strong background and achievement in mathematics demonstrates my aptitude as a scientist, which I have applied in my project for learning complex methods. I have succeeded in extremely difficult math courses at White Plains High School, such as AP BC Calculus and Multivariable Calculus. In these classes, I picked up mathematical skills quite quickly. This ability also applies to my future career as a scientist because I will be able to acquire certain skills more easily. For example, my project required me to learn countless technical skills like from navigating the command line to programming in at least 4 new languages, and managing datasets containing hundreds of separate files. I demonstrated my ability to learn new skills when my mentor asked me to apply a method I complex calculus-based method called wavelet analysis. Consequently, I watched a recording of a difficult university lecture and derived the necessary details to implement wavelet analysis in my methods.

My scientific and technical ability extends beyond my project. I have spent hours experimenting with my computer, learning how operating systems work, picking up programming languages, and even learning the basics of hacking (legal of course!). Through these activities, I have honed my technology skills while gaining a deep understanding of how the world's computing infrastructure functions.

In college, I plan to focus on physics while also pursuing computer science and more scientific research. I am unsure of my career plans, but I can imagine myself as an industry climatologist or data scientist.

* Major Scientific Question (maximum 250 words)
What is a major scientific question in your field whose answer you believe will have a significant impact on the world in the next 20 years, and why? Using examples from your own experience or research, explain how you might envision addressing the question over the next 20 years.

Climate predictions are usually grouped into three categories based on human greenhouse gas emissions: worst case, average case, and best case. Under the worst case predictions, environmental regulation is minimal, and industry continues with the same practices it has today. In the best case scenario, renewable energy becomes widespread and fossil fuel burning all but stops. The average case is between the best and worst cases. The major question in my field is which pathway is the most accurate? If humans continue to emit greenhouse gasses like we are doing now, then climatologists' worst predictions will come true, but if we implement strict regulations and switch to renewable energy, much of this disaster may be averted. The answer to this question will determine which set of predictions is most applicable for helping humans to respond to climate change.

I would go about answering this question by comparing characteristics such as El Niño from climate models to those in the observed record of the climate. By correlating these characteristics with levels of greenhouse gas emissions in the observed and simulated climate.

* "Tweet" about your project! Tell us about your project in 280 characters or less.
The Society might share this response if you are named a scholar or finalist.

Models show that CO2 emissions are causing El Niño to become stronger due to global warming. My analysis of climate predictions shows that El Niño's strength is increasing, which could cause more extreme weather.

* TODO Greatest Accomplishment or Challenge (COMMON APP)
Please answer ONE of the prompts below from the Common App; we prefer that you think beyond your research project in this essay. (maximum 200 words)
Discuss an accomplishment, event, or realization that sparked a period of personal growth and a new understanding of yourself or others.
OR
The lessons we take from obstacles we encounter can be fundamental to later success. Recount a time when you faced a challenge, setback, or failure. How did it affect you, and what did you learn from the experience?

* About You (COMMON APP) (optional)
Some students have a background, identity, interest, or talent that is so meaningful they believe their application would be incomplete without it. If this sounds like you, then please share your story. (maximum 200 words)

*  COVID-19 Pandemic (adapted from COMMON APP) (optional)

The COVID-19 pandemic has been experienced differently throughout the country and world. Share how it has impacted your life, especially its impact on your learning and as applicable on your submitted project and ability to work on that project. Examples include:
- Illness or loss within your family or support network
- Employment or housing disruptions within your family
- Food insecurity
- Toll on mental and emotional health
- New obligations such as part-time work or care for siblings or family members
- Availability of computer or internet access required to continue your studies
- Access to a safe and quiet study space
- A new direction for your major or career interests
