#+TITLE: Regeneron STS Application Essay Questions
# #+LATEX_CLASS: basic
# #+LATEX_CLASS_OPTIONS: [little]
#+OPTIONS: toc:nil

* Research Project “Layperson’s Summary” (maximum 200 words)
Summarize your project in layperson’s terms, while maintaining scientific accuracy. Your explanation should be easily understandable and include background, procedures, conclusions and relevance. This summary will aid readers, including evaluators, journalists and the public.


* Project Benefits and Impact (maximum 200 words)
What benefits do you think your research will bring to the world, and/or to your field? What additional steps, and by whom, might be needed for this benefit to be realized?


* Your Potential as a Scientist, Mathematician or Engineer (maximum 250 words)
Address through specific and concrete examples what characteristics you have that best demonstrate your affinity and aptitude for being a good scientist.
- What have you done that illustrates scientific aptitude, leadership, curiosity, inventiveness and/or initiative?
- After completing your research, how has your interest in science, engineering, and/or math been clarified? What are your other STEM-related interests besides your project?
- How does your experience suggest future success as a scientist, mathematician or engineer?
- What do you plan to study in post-secondary education and what occupation do you plan to pursue?  What do you hope to be doing 10 years from now?


* Major Scientific Question (maximum 250 words)
What is a major scientific question in your field whose answer you believe will have a significant impact on the world in the next 20 years, and why? Using examples from your own experience or research, explain how you might envision addressing the question over the next 20 years.


* "Tweet" about your project! Tell us about your project in 280 characters or less.
The Society might share this response if you are named a scholar or finalist.

* Greatest Accomplishment or Challenge (COMMON APP)
Please answer ONE of the prompts below from the Common App; we prefer that you think beyond your research project in this essay. (maximum 200 words)
Discuss an accomplishment, event, or realization that sparked a period of personal growth and a new understanding of yourself or others.
OR
The lessons we take from obstacles we encounter can be fundamental to later success. Recount a time when you faced a challenge, setback, or failure. How did it affect you, and what did you learn from the experience?

* About You (COMMON APP) (optional)
Some students have a background, identity, interest, or talent that is so meaningful they believe their application would be incomplete without it. If this sounds like you, then please share your story. (maximum 200 words)

*  COVID-19 Pandemic (adapted from COMMON APP) (optional)

The COVID-19 pandemic has been experienced differently throughout the country and world. Share how it has impacted your life, especially its impact on your learning and as applicable on your submitted project and ability to work on that project. Examples include:
- Illness or loss within your family or support network
- Employment or housing disruptions within your family
- Food insecurity
- Toll on mental and emotional health
- New obligations such as part-time work or care for siblings or family members
- Availability of computer or internet access required to continue your studies
- Access to a safe and quiet study space
- A new direction for your major or career interests
