#+TITLE: Research Plan for the Impact of Anthropogenic Forcing on ENSO Amplitude
#+AUTHOR: Benjamin Goldman
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[letterpaper, margin=1in]{geometry}
#+OPTIONS: toc:nil


* Rationale

El Niño/Southern Oscillation (ENSO) is a cyclical change in the temperature of the equatorial Pacific Ocean. It is accompanied by disturbances to the Walker Circulation and reduced upwelling in the eastern Pacific citep:bjerknes1969atmospheric. ENSO has extreme effects on global climate, affecting the intensity of rainfall in the Americas, the location of Rossby Waves, the paths of storms, and much more citep:liu2007atmospheric. Because of these critical effects, determining how climate change will affect ENSO is crucial.

Scientists have begun to research the effects of natural and anthropogenic forcing on ENSO. For example, citet:zhu2017reduced showed that during the Last Glacial Maximum, lower CO$_2$ levels reduced ENSO variability. cite:levine2017impact suggested that the Atlantic Multidecadal Oscillation (AMO) may also play a role in determining ENSO amplitude and demonstrated the difficulty in predicting long-term changes to ENSO. Researchers have also shown the effect of natural forcing on ENSO variability. citet:zheng2018response showed that ENSO variability is highly dependent on internal variability, and therefore a model with a large ensemble is necessary to measure a robust signal. Despite the copious noise in the simulated ENSO amplitude record, progress has been made in determining the sign of changes to ENSO amplitude over the 21st century. Recent studies citep:maher2018enso, citep:cai2018increased suggest that ENSO is likely to intensify, using records of increased ENSO amplitude in large model ensembles as evidence.

These past studies provide a background of predicted increased ENSO amplitude. With this background as a starting point, this study aims to assess probable causes for this predicted increasing amplitude. Using 2 recent derivatives of the National Center for Atmospheric Research's (NCAR) Community Earth System Model version 1 (CESM1), the CESM1 Large Ensemble and the CESM1 Single Forcing Ensembles. Using these tools, significant increases to ENSO amplitude over the 21st century were attributed to the combined influence of greenhouse gases and aerosol emissions on ocean stratification and mixed layer heat transfer. However, some questions remain, and new data sources beckon. Firstly, past results conducted indicate a predicted decrease in ENSO amplitude after approximately 2060, which the researchers aim to investigate. Additionally, the sign of changes to ENSO amplitude under greenhouse forcing agree with those under aerosol forcing, where other studies indicated that they should be the opposite due to the differing nature of greenhouse and aerosol emissions citep:deser2020isolating. Moreover, it is still unclear specifically how greenhouse and aerosol emissions affect mixed layer heat transfer. Finally, Large Ensemble and Single Forcing runs are nearly complete for NCAR's next generation of the CESM, CESM2. Past methods will be repeated on this dataset and results will be compared to those from the CESM1, with the hope that the CESM2 results will provide insight into those descrepancies that appear in the CESM1 output. Additionally, deeper analysis of the role of air currents and ocean structure will be conducted for each ensemble to further clarify the processes that mediate the aforementioned forced effect on ENSO amplitude.

* Research Goals
- Estimate future changes to ENSO amplitude in the NCAR's Community Earth System Model Version 2 (CESM2)
- Compare these changes to those previously found in the CESM1.
- Examine contributions of greenhouse gasses, aerosols, and natural forcing in both models.
- Explore physical mechanism that mediates emissions' effect on ENSO amplitude.

* Methods
** Materials and Data
- NCAR's CESM1 and CESM2 will be used.
  + Fully forced historical and projected simulations.
  + Single forcing simulations that are forced by all but one factor.
- The Python and R programming language will be used with third party packages as needed.

** Procedures
/Methods are subject to change in response to results/
- Wavelet transform will be conducted on the Niño 3.4 index of each member of the CESM1 and CESM2 ensembles.
- The mean wavelet power spectrum will be calculated and graphed
- The mean power spectrum will be divided into two frequency bands, that with a period greater than 3 years, and one with a period less than three years.
- The ensemble mean and standard error will be calculated for both frequency bands

** Risk and Safety
No risk/safety issues relevant as all methods are digital.

* Role of Mentor and Student
| Student                     | Shared                         | Mentor                     |
|-----------------------------+--------------------------------+----------------------------|
| Perform all calculations    | Discuss and interpret results | Review results and methods |
| Produce plots and documents |                                | Provide large datasets     |
|                             |                                | Check student work         |

bibliographystyle:apalike
bibliography:references.bib
