#+TITLE: Script
#+LATEX_CLASS: basic
#+LATEX_HEADER: \class{Science Research}
#+LATEX_HEADER: \professor{Ms. Fleming}
#+OPTIONS: toc:nil

Hello, my name is Ben Goldman, and I am presenting my study called "The impact of anthropogenic forcing on ENSO amplitude." You've probably heard about some kind of extreme weather in the news, or experienced an unusually hot or cold year. This phenomenon is most likely caused by El Nino.

El Nino, which researchers also refer to as El Nino Southern Oscillation, or ENSO, is a crucial element of the climate system. El Nino, or ENSO, is a change in the temperature of the equatorial Pacific Ocean. This change in temperature leads to disruption of air currents and changes in rainfall. ENSO is often responsible for extreme weather, such as the catastrophic flooding in South America during the 2016 event. Due to this extreme impact, it is important for people to predict ENSO, which is what my study is focused on.

The earth's climate is very complex because it changes in a variety of ways, namely long-term and short-term. The red line on this graph of global air temperature from 1880 to the present depicts a long-term change, in this case global warming, which is caused by human greenhouse gas emissions. However, the climate also changes on short timescales, over the course of years instead of decades, as shown by the jagged black line. ENSO is one example of this short-term variability. Studying climate is often difficult because it may be unclear whether certain events can be attributed to short-term effects, long-term effects, or both. My study is on how short and long-term variability interact with each other, or more specifically, how do long term changes in global temperature affect the intensity of short-term changes, in this case, ENSO?

Scientists have attempted to answer this question of global warming's influence on ENSO, mainly using computer simulations of the earth's climate. Many researchers who ran these simulations found that ENSO is predicted to become more intense, while others predicted a weakening. In 2017, Chen et. al. found that differences between simulations's modeling of air movement above the Pacific Ocean was largely responsible. However, in recent years, it's become clear that ENSO is more likely to intensify rather than weaken, as studies like Maher et. al. (2018) showed that in a large group of simulations, a majority of them showed increased ENSO strength. Also, Cai et. al. (2018) showed that by using a more flexible method of measuring ENSO events, a majority of simulations predict increased ENSO intensity. It has also become clear that ENSO is intensifying due to increasing ocean stratification, or the temperature difference between the upper and central layers of the pacific ocean. However, it is still unclear what human activities are causing ENSO to intensify, so the aim of my study is to assess the role of greenhouse gasses in comparison to aerosols and natural changes in forcing increased ENSO amplitude.

 So my first goal of this study is to measure predicted changes to ENSO intensity, judging whether they agree with those documented in past research. The next goal is to analyze the relative role of greenhouse gasses, like carbon dioxide, and aerosols, such as smoke and dust, in affecting ENSO intensity in the future. This will enable me to figure out what human activities are contributing most to ENSO intensification. Finally, I intended to examine changes to stratification and heat transfer under greenhouse and aerosol forcing, to examine what is actually happening on the planet that translates increased temperature into strengthened ENSO.

All of my data so far comes from a computer simulation of the climate, an estimation of the Earth's climate using mathematical equations. These equations allow researchers like me to make predictions about what will happen in the future if humans continue polluting the environment. I used an experimental group that simulates future changes to the entire Earth's climate with predicted increases in greenhouse and aerosol emissions, and a control group that uses fixed preindustrial levels of pollutants.

My first step was to measure ENSO intensity in the simulation output. To do this, I averaged sea surface temperature in the Niño 3.4 box of the Pacific ocean, shown in this blue box. Then, I converted this temperature record into a record of ENSO intensity with a 20-year sliding windowed variance calculation. By finding variance around one point, and then moving that point forward one month, I derived a dataset capturing ENSO intensity changing over time.

This plot shows the results of my calculation. Each line represents ENSO intensity in each member of the dataset. Notice that they start out close together, and then gradually diverge over time. This is an example of the butterfly effect, where small differences in initial conditions evolve into significant differences. This chaotic property of climate means that by itself, each simulation run is quite inaccurate, but by taking the average of running a simulation multiple times, one can filter out a great deal of this noise.

ENSO is predicted to intensify in the future, as shown in this graph. The blue bar shows variance in the experimental simulations, while the grey bar shows that of the control. There is a significant increase over time, meaning that ENSO is becoming stronger in the models. There is a decrease after 2060, which I am still investigating.

The next step is to determine how large of a role greenhouse emissions play versus aerosol emissions and natural factors. To do this, I had to separate the influence of each factor from the model output, by using simulations of the Earth's climate that used all but one category of influence. For example, the greenhouse gas dataset, or ensemble, was forced by aerosols and natural factors. Next, by subtracting this dataset from the original dataset which received all factors as input, I derived changes to ENSO intensity under only one single factor.

Here are the results for greenhouse gasses and aerosols, where the graph shows the portion of changes to ENSO intensity that are attributed only to these factors. Both the greenhouse gas and aerosol lines are above zero, meaning that they are contributing to ENSO intensity increasing. Natural factors were left out of this graph because their influences were all statistically insignificant. Interestingly, changes to ENSO intensity under aerosol emissions have the same sign as that from greenhouse gas emissions, where other studies predicted that aerosols should have an opposite effect from greenhouse gasses. Now both greenhouse gasses and aerosols are human-produced, meaning that the majority of changes to ENSO intensity are humanity's fault.

Finally, I looked at what changes to ocean structure occur under greenhouse and aerosol emissions, to determine what physical processes are mediating their influence. To do this, I calculated the correlation coefficient between ENSO intensity and sea temperature at the equator, after detrending and smoothing both inputs.

Shown here are the results of this process. Each plot represents a different forcing scenario. The fully-forced scenario exhibits a strongly negative correlation coefficient in the subsurface layer of the pacific, meaning that the temperature in that region is connected to ENSO intensity. This correlation coefficient is positive in the greenhouse gas-only dataset in the middle, and close to zero in the aerosol dataset in the third row. We believe that this region of the ocean is connected to ENSO intensity because rising air temperatures from the greenhouse effect lead to different layers of the ocean heating at different rates, affecting how heat is transferred during an ENSO event.

We can conclude from these results that ENSO will likely become more intense in the future, and that this increase can be attributed to a combination of greenhouse and aerosol emissions. These emissions affect ENSO intensity through modifying how heat is transferred between different layers of the ocean. These broad conclusions agree with past research such as Cai et. al. 2018, and more analysis is being done on those that do not, such as the sign of the changes to ENSO intensity in the aerosol-only simulation, conflicting with Deser et. al. 2020.

My research contributes to a growing body of evidence demonstrating that global warming causes extreme weather, which in turn, harms humans and natural ecosystems. Climate research like mine will continue to encourage people to limit their greenhouse gas emissions. This study has a few limitations, the most important of which being the fact that only one out of many existing models is used, and that the Niño 3.4 index has been shown to be inaccurate for certain models. The next steps for my research are to conduct similar analysis on the output from different models and to examine other possible mediators to ENSO intensity under global warming, such as air currents.

Thank you to the scientists at the National Center for Atmospheric Research for running the simulations that my research uses. Thank you to my family for their encouragement and enthusiasm for my project, and to my teacher for teaching me how to conduct research at this level. Thank you to my mentor for providing and compiling the raw data, for helping to interpret my results select methods, and for reviewing my work.

Thank you for listening.
