#+TITLE: Feedback for main presentation
#+LATEX_CLASS: basic
#+LATEX_CLASS_OPTIONS: [little]
#+OPTIONS: num:1, toc:nil

* Feedback 1
Date: <2021-09-26 Sun>
Time: 20:20
Listener: Abby Goldman
** Feedback
- lots of arm waving. SOOOOMUCH ARM WAVING!!! And very little breathing
- make a list of “overhead” - make sure all concepts are well defined, in your notes, possibly in your slides
- summary of what your many slides are — many different crunching of different data to circle around a process that we’re trying to under
- insert heading slides, overall need a good deal more organization.
- slide 1: break up into two or even 3?
- Slide 2: Need to explain more generally what’s in the figure
- Slide 3: climate simulation — is this method? If so, say so
- Slide 4: ENSO and climate change slide — have “literature review” in heading.
- slide about Mentor: do a better job explaining the interactive process between you and your mentor.
- 3.4 index - whahah? I didn’t follow
- Single forcing ensembles slide — not sure if all those arrows are working for you. Skip over single forcing setup, maybe?
- use consistent language about the aerosols and their influence, considering that it’s a prediction

* Feedback 2
Date: <2021-09-30 Thu>
Time: 8:20
Listener: Marcus Chung, Sean O'Donnell, Jimena Perez
** Feedback:
- Figure text is too small
- Caption text can be smaller to make room
- Say some transition for the conclusion heading slide
- Clarify difference between El Niño and La Niña
  + overall make intro 2 more organized
- Good understanding and well communicated
- Are some slides too empty-looking?
- Say fewer words because it is over time and talking too fast
- Use note cards
- Periods should be consistent.

* Feedback 3
Date: <2021-09-30 Thu>
Time: 16:00
Listener: Michael Goldman
** Feedback:
- Make a few bullets clearer
- Good tone
- Slow down pacing
- Introduction is slightly unclear
- Use note cards

* Feedback 4
Date: <2021-10-17 Sun>
Time: 17:12
Listener: Jimena Perez
** Feedback:
- Make figures bigger and make captions smaller
- Love how detailed the content is
- Great application slide
- Make sure you explain your results in the context of your study, think big picture
- Intro slide 2 is great we’ll explained

* Feedback 5

Date: <2022-01-06 Thu>
Time: 09:20
Listener: Jimena Perez
** Feedback:
- Put Student vs mentor role earlier in presentation
- Slow down speech
- Write a script for wavelet slide
- Don't admit you don't understand it
- No monospace for urls
- Clean up global warming slide

* Feedback 6

Date: <2022-01-15 Thu>
Time: 09:20
Listener: Abby Goldman
** Feedback
- Make some notes to follow
- Couple slides were unclear
- Speak slower and less nervous
- Good introduction

* Feedback 7
Date: <2022-01-20 Thu>
Time: 9:25
Listener: Jimena Perez
** Feedback:
- Love how the intro slides flow, the flow chart in the methodology slide becomes easier to understand every time you present it
- Maintain speaking pace, describe implications of methodology while you're going through methodolgy.

* Feedback 8
Date: <2022-01-25 Tue>
Time: 9:25
Listener: Sean O'Donnell
** Feedback:
- Don't have to say ziggy zaggy line on 2nd slide (say red line or blue line)
- Don't think you described figure 2
- Liked explanation of figure 3 and El Nino/La nina in general
- Yes, def mention ENSO first before EL Nino and La nina in introduction
- Liked simplicity of powerpoint design, made it very easy to follow
- Maybe mention CESM before stating research questions so people can understand its background (may not be necessary though)?
- Strong explanation of methodology (liked the flowchart)
- Liked the addition of "increasing variance" and decreasing variance" to Figure 4
- What's difference between CESM1 and CESM 2 (may have missed this in presentation)?
- Yes, def note software used before acknowledgements (don't have to describe each database)

* Feedback 9
Date: <2022-03-16 Wed>
Time: 9:25
Listener: Giovanni
** Feedback:
- Good overall
- Slow down
- Weird spacing

* Feedback 10
Date: <2022-03-17 Thu>
Time: 9:25
Listener: Nurashau
** Feedback:
- Slow down
- Weird spacing
- Mispronouncing "statistically"

* Feedback 11
Date: <2022-03-18 Fri>
Time: 9:25
Listener: Abby Goldman
** Feedback:
- Slow down
- Improve hook and application to be a little more specific
