#+TITLE: Celia Paper Feedback
#+DATE: 14 May 2021
#+LATEX_CLASS: basic
#+OPTIONS: toc:nil

* Abstract
- You might want to put everything in past tense or future tense, since the paper will be submitted after you have results
- Otherwise, it is very clear and concise
- Also, sometimes they say not to use first person. It seems fine as it is but Ms. Fleming might have a preference

* Introduction
- Paragraph 1 does a good job introducing the topic, I especially liked the last sentence about how light pollution is as of yet mostly unquantified.
- In the sentence with "...can easily accumulate over and light pollution is a problem..." I would turn the and into a sentence break so it is easier to read.
- For paragraph 2 when you cite a paper, you should use parenthetical citations
  + So like say "According to Longcore and Rich (2004), light pollution could ..." or "Light pollution could alter ... (Longcore and Rich 2004)."
- Expand a little bit on paragraph 2, maybe cite a few more recent papers, and say how they affect your hypothesis by creating a gap.
- I would only include the figure if it directly supports the ideas in the introduction. Its a cool picture, but I'm not sure its necessary. Maybe you could use like a picture of sources of light pollution or something.
- Maybe in the 3rd paragraph elaborate a little bit on the dependent variable, so like say what the implications of a high light level are, etc.
- Are you examining how light pollution is changing over time, or on average in a certain time span, or only in the present?
- Similar citation thing for p. 4.
- Add a sentence or 2 after each paper citation to add more for how it impacts your study or other studies.
- For the last intro paragraph, you mention your hypothesis being supported, but it's not clear what your hypothesis actually is.
- The part about the designation being worth it or not is interesting, and because it would be an implication of your results, you should clarify what you mean about it.
- You could also mention ecosystems and human health in addition to tourism
- Not clear what the gap in literature is
- Overall, you did a good job introducing each paper so that they all contribute to your study, but what's missing is an explanation of the importance of each paper, and the gap.

* Methodology
- Do a separate paragraph on data where you talk about where the raw lighting data is coming from. Is it satellites, human recordings, some kind of meter, etc?
- Median
- I think past or present tense would work fine here too.
- You mentioned using ANOVA?
