#+TITLE: Abstract
#+OPTIONS: title:nil, toc:nil, author:nil, num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

#+BEGIN_CENTER
*The Impact of Industrial Emissions on ENSO Amplitude*

*Benjamin Goldman*

#+END_CENTER

The El Niño/Southern Oscillation (ENSO) is the dominant mode of interannual climate variability, with substantial associated global socio-economic impacts. Due to their significance, shifts in ENSO under climate change also have the potential to substantially impact human society and natural ecosystems. However, it is currently unclear what effect greenhouse gas and industrial aerosol emissions have on ENSO, as well as what effect these factors have when combined. This study examined transient changes to ENSO variance under a variety of forcing scenarios using the CESM1 and CESM2 Large and Single-Forcing Ensembles. These multi-member ensembles span the historical record (1920-2005) and much of the 21st century (2006-2080 for GHG/AER). A 2000-year pre-industrial (PI) control simulation is used to account for model drift and 20-year running variance of the Niño 3.4 SST index is used as a proxy for ENSO variance. The ensemble mean and standard error of each ensemble was calculated, while the Probability Density Function (PDF) is computed for the PI control simulation to estimate the statistical significance of simulated changes. I calculated the correlation coefficient between ocean temperature in the equatorial Pacific and Niño 3.4 under various forcing conditions, concluding that Pacific stratification likely is tied to changes to ENSO amplitude. Finally, I examined the wavelet power spectrum of the historical and predicted Niño 3.4 index to support the data given from the 20-year variance calculation. I identified significant increases in variance of the Niño 3.4 index under full-forcing conditions during the historical record and attribute these mainly to changes in GHG, with the potential emergence of AER-driven increases in the decades to come.

#+BEGIN_CENTER
*Presentations*
#+END_CENTER

*2020:* /Virtual Poster Board presenter at the White Plains High School Science Research Symposium (June)/

*2021:* /Virtual Powerpoint presenter at the Westchester Science and Engineering Fair (March)/

#+BEGIN_CENTER
*Awards*
#+END_CENTER

*2021:* /American Meteorological Society Award at the Westchester Science and Engineering Fair/

*2021:* /4^{th} Place in Earth Science at the Westchester Science and Engineering Fair/

#+BEGIN_CENTER
*Mentor Information*

Dr. John Fasullo

National Center for Atmospheric Research

Boulder, Colorado
#+END_CENTER
